//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konveter_valyut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int ID { get; set; }
        public string CurrencyNameOne { get; set; }
        public string CurrencyNameTwo { get; set; }
        public Nullable<double> CurrencyValueOne { get; set; }
        public Nullable<double> CurrencyValueTwo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
    }
}
